//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimDetail
    {
        public int ClaimNo { get; set; }
        public Nullable<decimal> UserMobNo { get; set; }
        public Nullable<int> VehId { get; set; }
        public Nullable<int> PolNo { get; set; }
        public string ClaimReason { get; set; }
        public string ClaimStatus { get; set; }
        public decimal ClaimAmt { get; set; }
        public System.DateTime ClaimDate { get; set; }
    
        public virtual PolicyDetail PolicyDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual VehicleDetail VehicleDetail { get; set; }
    }
}
