//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public string UserName { get; set; }
        public string Email { get; set; }
        public string MobNo { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}
