//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeneralInsuranceEntities : DbContext
    {
        public GeneralInsuranceEntities()
            : base("name=GeneralInsuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClaimDetail> ClaimDetails { get; set; }
        public DbSet<PolicyDetail> PolicyDetails { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<VehicleDetail> VehicleDetails { get; set; }
    }
}
