//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotorClaimDetailsTable
    {
        public long Claim_Id { get; set; }
        public Nullable<int> Policy_Id { get; set; }
        public string Name { get; set; }
        public string Mobile_Number { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Date_Of_Applying { get; set; }
        public string Insurance_Copy { get; set; }
        public string License_Copy { get; set; }
        public string RC_Copy { get; set; }
        public string Authenticated_Letter_from_RTO { get; set; }
        public Nullable<double> Estimated_Amount_For_Repair { get; set; }
        public string Bill_Copy { get; set; }
        public Nullable<double> Amount_Sanctioned { get; set; }
        public string Claim_Status { get; set; }
    
        public virtual PolicyDetail PolicyDetail { get; set; }
    }
}
