//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        public int TicketNo { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime DateOfTravel { get; set; }
        public int NoOfPassengers { get; set; }
        public decimal ValidityOfInsurance { get; set; }
    }
}
