//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInsurance
    {
        public TravelInsurance()
        {
            this.TravelClaimDetails = new HashSet<TravelClaimDetail>();
        }
    
        public int PolicyNo { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime TripStart { get; set; }
        public System.DateTime TripEnd { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public decimal MobileNo { get; set; }
        public int NoOfPassengers { get; set; }
        public string IPlan { get; set; }
    
        public virtual ICollection<TravelClaimDetail> TravelClaimDetails { get; set; }
    }
}
