//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public UserDetail()
        {
            this.ClaimDetails = new HashSet<ClaimDetail>();
            this.PolicyDetails = new HashSet<PolicyDetail>();
            this.VehicleDetails = new HashSet<VehicleDetail>();
        }
    
        public decimal MobNo { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual ICollection<ClaimDetail> ClaimDetails { get; set; }
        public virtual ICollection<PolicyDetail> PolicyDetails { get; set; }
        public virtual ICollection<VehicleDetail> VehicleDetails { get; set; }
    }
}
