//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public VehicleDetail()
        {
            this.ClaimDetails = new HashSet<ClaimDetail>();
            this.PolicyDetails = new HashSet<PolicyDetail>();
        }
    
        public int VehicleID { get; set; }
        public Nullable<decimal> UserMobNo { get; set; }
        public string Maufacturer { get; set; }
        public string Model { get; set; }
        public string VehicleType { get; set; }
        public string DrivingLicense { get; set; }
        public string RegistrationNo { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
    
        public virtual ICollection<ClaimDetail> ClaimDetails { get; set; }
        public virtual ICollection<PolicyDetail> PolicyDetails { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
