//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelClaimDetail
    {
        public int Travel_Claim_Id { get; set; }
        public Nullable<int> PolicyNo { get; set; }
        public string Reason_for_Claim { get; set; }
        public string MobNo { get; set; }
        public decimal Amount { get; set; }
        public string Claim_Status { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual TravelInsurance TravelInsurance { get; set; }
    }
}
